services:
  magpie:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - path: backend/.env
        required: false
    volumes:
      - ./downloads:/app/downloads
      - ./data:/app/data
    restart: unless-stopped
